id: IB7FF7B8A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T09:00:52+00:00'
last_modified: '2022-06-09T04:57:32.129741+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1084
  title: གསུང་འབུམ། ཐོགས་མེད་བཟང་པོ་དཔལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    35BC:
      image_group_id: I1CZ1459
      title: ''
      total_pages: 192
      order: 1
      base_file: 35BC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
